### ISSUE TITLE
plotter.py OSEror

### ISSUE THREAD

**Issue by Sullinberg** [marcoschulte/lego-wallplotter#2]
using ampy
`sudo ampy -p /dev/rfcomm0 run /plotter/plotter.py`
im ge tiing following error:

Caught exception [Errno 2] ENOENT
Traceback (most recent call last):
  File "<stdin>", line 389, in plot_file
  File "<stdin>", line 189, in __init__
  File "<stdin>", line 192, in _open_file
OSError: [Errno 2] ENOENT
Motor pos [0, 0]

Any advice on solving this issue?

**Comment by marcoschulte** [comment]
Hi Sullinberg,
it fails in line 192, where it tries to open the image file. Most likely the path you are passing in `plotter.plot_file('your-file-path.txt')` is wrong
